"""SQLAlchemy declarative base and shared model mixins.

Every table in the app inherits from `Base` plus the mixins it needs, so
primary keys and timestamps are defined once rather than copy-pasted.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

#: Template for constraint and index names.
#:
#: Without this, PostgreSQL invents names like `provider_profiles_user_id_key`
#: and Alembic cannot reliably drop or alter them later — autogenerated
#: downgrades break. With it, every constraint has a predictable name, so
#: migrations stay reversible. Set it before writing the first model; changing
#: it afterwards means renaming every existing constraint.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for all ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    """A UUID primary key.

    Why UUID rather than an auto-incrementing integer:

    - Sequential ids are guessable. `/vehicles/124` invites a client to try
      123 and 125 — and if an ownership check is ever missed, that becomes a
      data leak (the BOLA risk in docs/PROJECT.md).
    - Integer ids leak business information: a competitor reading
      `/providers/57` learns you have 57 providers.
    - Ids can be generated by the app before insert, which makes tests and
      future data merging simpler.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )


class TimestampMixin:
    """Automatic created_at / updated_at.

    `server_default=func.now()` means PostgreSQL sets the value, not Python.
    That keeps timestamps consistent even if an app server's clock drifts, and
    it still works for rows inserted by a migration or by hand in psql.

    `DateTime(timezone=True)` stores an aware UTC timestamp. Never store naive
    datetimes — converting to IST for display is the client's job.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
