"""add_bookings_favourites_reviews_notifications_geometry

Revision ID: a1e2d6ed1a65
Revises: 171ff741f85d
Created: 2026-08-19 13:33:51.891725+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import MetaData


revision: str = 'a1e2d6ed1a65'
down_revision: str | None = '171ff741f85d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('BOOKING_REQUEST', 'BOOKING_ACCEPTED', 'BOOKING_REJECTED', 'BOOKING_CANCELLED', 'CALL_INITIATED', 'NEW_REVIEW', name='notification_type', ), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read_created', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_table('bookings',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('renter_user_id', sa.UUID(), nullable=False),
    sa.Column('provider_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'ACTIVE', 'COMPLETED', 'REJECTED', 'CANCELLED', name='booking_status', ), server_default='PENDING', nullable=False),
    sa.Column('booking_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session', sa.Enum('MORNING', 'AFTERNOON', 'EVENING', 'FULL_DAY', name='session_block', ), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('renter_note', sa.Text(), nullable=True),
    sa.Column('provider_note', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_paise > 0', name=op.f('ck_bookings_amount_paise_positive')),
    sa.CheckConstraint('duration_hours BETWEEN 1 AND 24', name=op.f('ck_bookings_duration_hours_valid')),
    sa.ForeignKeyConstraint(['provider_user_id'], ['users.id'], name=op.f('fk_bookings_provider_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['renter_user_id'], ['users.id'], name=op.f('fk_bookings_renter_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_bookings_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings'))
    )
    op.create_index('ix_bookings_provider', 'bookings', ['provider_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_bookings_provider_user_id'), 'bookings', ['provider_user_id'], unique=False)
    op.create_index(op.f('ix_bookings_reference'), 'bookings', ['reference'], unique=True)
    op.create_index('ix_bookings_renter', 'bookings', ['renter_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_bookings_renter_user_id'), 'bookings', ['renter_user_id'], unique=False)
    op.create_index(op.f('ix_bookings_vehicle_id'), 'bookings', ['vehicle_id'], unique=False)
    op.create_table('favourites',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favourites_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_favourites_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favourites')),
    sa.UniqueConstraint('user_id', 'vehicle_id', name='uq_favourites_user_vehicle')
    )
    op.create_index('ix_favourites_user_created', 'favourites', ['user_id', 'created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_favourites_user_id'), 'favourites', ['user_id'], unique=False)
    op.create_index(op.f('ix_favourites_vehicle_id'), 'favourites', ['vehicle_id'], unique=False)
    op.create_table('reviews',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_reviews_ck_reviews_rating_range')),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], name=op.f('fk_reviews_reviewer_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_reviews_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('vehicle_id', 'reviewer_user_id', name='uq_reviews_vehicle_reviewer')
    )
    op.create_index(op.f('ix_reviews_reviewer_user_id'), 'reviews', ['reviewer_user_id'], unique=False)
    op.create_index('ix_reviews_vehicle_created', 'reviews', ['vehicle_id', 'created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_reviews_vehicle_id'), 'reviews', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_vehicle_id'), table_name='reviews')
    op.drop_index('ix_reviews_vehicle_created', table_name='reviews', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('ix_reviews_reviewer_user_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_favourites_vehicle_id'), table_name='favourites')
    op.drop_index(op.f('ix_favourites_user_id'), table_name='favourites')
    op.drop_index('ix_favourites_user_created', table_name='favourites', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_table('favourites')
    op.drop_index(op.f('ix_bookings_vehicle_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_renter_user_id'), table_name='bookings')
    op.drop_index('ix_bookings_renter', table_name='bookings')
    op.drop_index(op.f('ix_bookings_reference'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_provider_user_id'), table_name='bookings')
    op.drop_index('ix_bookings_provider', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('ix_notifications_user_read_created', table_name='notifications', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
