"""add_postgis_geometry_to_vehicles

Revision ID: 522c1f6d69c7
Revises: a1e2d6ed1a65
Created: 2026-08-19 13:42:31.369042+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '522c1f6d69c7'
down_revision: str | None = 'a1e2d6ed1a65'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favourites_user_created'), table_name='favourites')
    op.create_index('ix_favourites_user_created', 'favourites', ['user_id', 'created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('ix_notifications_user_read_created'), table_name='notifications')
    op.create_index('ix_notifications_user_read_created', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('ix_reviews_vehicle_created'), table_name='reviews')
    op.create_index('ix_reviews_vehicle_created', 'reviews', ['vehicle_id', 'created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_vehicle_created', table_name='reviews', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_reviews_vehicle_created'), 'reviews', ['vehicle_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('ix_notifications_user_read_created', table_name='notifications', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_notifications_user_read_created'), 'notifications', ['user_id', 'is_read', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('ix_favourites_user_created', table_name='favourites', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_favourites_user_created'), 'favourites', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
